name: whatsapp_monitor
description: A Flutter app to monitor WhatsApp UI events
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  intl: ^0.20.2
  permission_handler: ^11.4.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env